Run eslint against relevant changed files in pre-push hook [DEV-26]
Plus, make some minor tweaks and improvements to the Gitleaks and
Prettier pre-push hook scripts.

diff --git a/bin/lint/gitleaks b/bin/lint/gitleaks
--- a/bin/lint/gitleaks
+++ b/bin/lint/gitleaks
@@ -2,9 +2,11 @@
 
 # Run Gitleaks.
 
-set -uo pipefail # don't allow undefined variables, pipes don't swallow errors
+set -euo pipefail # exit on any error, don't allow undefined variables, pipes don't swallow errors
 
 # Use gitleaks to protect against committed secrets.
 if ! gitleaks detect --log-opts="origin/main..." &> /dev/null ; then
   gitleaks detect --log-opts="origin/main..." --verbose
+else
+  echo 'Gitleaks did not detect any committed secrets.'
 fi
diff --git a/bin/lint/prettier b/bin/lint/prettier
--- a/bin/lint/prettier
+++ b/bin/lint/prettier
@@ -2,17 +2,17 @@
 
 # Run Prettier.
 
-set -uo pipefail # don't allow undefined variables, pipes don't swallow errors
+set -euo pipefail # exit on any error, don't allow undefined variables, pipes don't swallow errors
 
 # Every file must have a period somewhere (either a dotfile or file extension).
 # Ruby files aren't linted by Prettier.
 files_for_prettier=$(
   changed-not-deleted-files | \
     rg '\.' | \
-    rg -v '\.(haml|lock|rb)$'
+    rg -v '\.(haml|lock|rb)$' || \
+    true
 )
 
-set -e # exit on any error
 
 if [[ $files_for_prettier != "" ]]; then
   set -x # print executed commands
@@ -32,4 +32,6 @@ if [[ $files_for_prettier != "" ]]; then
 
     exit 1
   fi
+else
+  echo 'No files needed to be linted by Prettier.'
 fi
